### ISSUE TITLE
TypeError: Cannot read property 'player_response' of undefined

### ISSUE THREAD

**Issue by ItsRohan0165** [MonsterMannen/DiscordBotNodeJs#9]
everything about the bot is gucci apart from when i run play it throws out this error

D:\New folder\DiscordBotNodeJs-master\audioprovider.js:48
            let min = ~~(info.player_response.videoDetails.lengthSeconds / 60);
                              ^

TypeError: Cannot read property 'player_response' of undefined
    at YTDL.getInfo (D:\New folder\DiscordBotNodeJs-master\audioprovider.js:48:31)
    at request (D:\New folder\DiscordBotNodeJs-master\node_modules\ytdl-core\lib\info.js:226:7)
    at IncomingMessage.res.on (D:\New folder\DiscordBotNodeJs-master\node_modules\miniget\lib\index.js:76:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by MonsterMannen** [comment]
These audio libraries always crash or do something weird >:(

Works again after some small changes.
